// =============================================================================
// lib/boq/__tests__/pricing-skus.fixture.ts
//
// Up to two SKUs per (category, subcategory) from the real pricing_skus table,
// captured 2026-09-05 — enough that every pool the R-xx rules reach is
// non-empty, without committing all 600 rows.
//
// Data, not judgement. Re-export rather than hand-editing a price.
// =============================================================================

import type { PricingSku } from "../schema";

export const PRICING_SKUS_FIXTURE = [
  {
    "id": "03d5b0b5-d187-4529-8b14-1954392909f5",
    "sku": "RAK-MRB-MAXIMUSC-60X60",
    "brand": "RAK Ceramics",
    "category": "Tiles",
    "subcategory": "Marble Effect Porcelain",
    "description_en": "Maximus Classic marble-effect porcelain floor & wall tile, Polished, 60x60 cm",
    "unit": "sqm",
    "price_aed": 120,
    "vendor": "RAK Ceramics",
    "in_stock": true
  },
  {
    "id": "77bd479d-66c3-474f-9eeb-0f5f12c2a0a4",
    "sku": "RAK-MRB-MAXIMUSC-60X120",
    "brand": "RAK Ceramics",
    "category": "Tiles",
    "subcategory": "Marble Effect Porcelain",
    "description_en": "Maximus Classic marble-effect porcelain floor & wall tile, Polished, 60x120 cm",
    "unit": "sqm",
    "price_aed": 137,
    "vendor": "RAK Ceramics",
    "in_stock": true
  },
  {
    "id": "4a6840f9-1cac-4ea5-bed7-1d84a2370ec8",
    "sku": "RAK-CON-ENDORA-60X60",
    "brand": "RAK Ceramics",
    "category": "Tiles",
    "subcategory": "Concrete Effect",
    "description_en": "Endora concrete effect tile 60x60 cm",
    "unit": "sqm",
    "price_aed": 87,
    "vendor": "RAK Ceramics",
    "in_stock": true
  },
  {
    "id": "d493fb6a-0f38-49f5-873a-b88f3956bfa0",
    "sku": "RAK-CON-ENDORA-60X120",
    "brand": "RAK Ceramics",
    "category": "Tiles",
    "subcategory": "Concrete Effect",
    "description_en": "Endora concrete effect tile 60x120 cm",
    "unit": "sqm",
    "price_aed": 113,
    "vendor": "RAK Ceramics",
    "in_stock": true
  },
  {
    "id": "5dfcbdfc-5214-4844-a515-eff18e671931",
    "sku": "RAK-CON-OROBICOC-60X60",
    "brand": "RAK Ceramics",
    "category": "Tiles",
    "subcategory": "Stone Effect Porcelain",
    "description_en": "Orobico stone effect porcelain tile 60x60 cm",
    "unit": "sqm",
    "price_aed": 68,
    "vendor": "RAK Ceramics",
    "in_stock": true
  },
  {
    "id": "f1e1419f-4933-40d9-9f22-6abe863a32e0",
    "sku": "RAK-CON-OROBICOC-60X120",
    "brand": "RAK Ceramics",
    "category": "Tiles",
    "subcategory": "Stone Effect Porcelain",
    "description_en": "Orobico stone effect porcelain tile 60x120 cm",
    "unit": "sqm",
    "price_aed": 111,
    "vendor": "RAK Ceramics",
    "in_stock": true
  },
  {
    "id": "6e24fddb-1563-4196-9617-057decc35761",
    "sku": "RAK-CON-STONEEFF-60X60",
    "brand": "RAK Ceramics",
    "category": "Tiles",
    "subcategory": "Outdoor Porcelain",
    "description_en": "Outdoor Stone Effect outdoor porcelain tile 60x60 cm",
    "unit": "sqm",
    "price_aed": 76,
    "vendor": "RAK Ceramics",
    "in_stock": true
  },
  {
    "id": "66d772a8-37b2-4c6e-9fb0-dd4c899c2466",
    "sku": "RAK-CON-STONEEFF-60X120",
    "brand": "RAK Ceramics",
    "category": "Tiles",
    "subcategory": "Outdoor Porcelain",
    "description_en": "Outdoor Stone Effect outdoor porcelain tile 60x120 cm",
    "unit": "sqm",
    "price_aed": 119,
    "vendor": "RAK Ceramics",
    "in_stock": true
  },
  {
    "id": "2c02d2b8-ef81-48a8-87fc-da3aba3cd20c",
    "sku": "RAK-CON-800SERIE-60X60",
    "brand": "RAK Ceramics",
    "category": "Tiles",
    "subcategory": "Glazed Porcelain",
    "description_en": "800 Series glazed porcelain tile 60x60 cm",
    "unit": "sqm",
    "price_aed": 90,
    "vendor": "RAK Ceramics",
    "in_stock": true
  },
  {
    "id": "841671d1-e68a-4352-99e2-56818377c78b",
    "sku": "RAK-CON-800SERIE-60X120",
    "brand": "RAK Ceramics",
    "category": "Tiles",
    "subcategory": "Glazed Porcelain",
    "description_en": "800 Series glazed porcelain tile 60x120 cm",
    "unit": "sqm",
    "price_aed": 101,
    "vendor": "RAK Ceramics",
    "in_stock": true
  },
  {
    "id": "726b77ff-5f83-4aab-80ab-3cac57025d07",
    "sku": "RAK-ES-01-LIQUIDME-60X120",
    "brand": "RAK Ceramics (Elie Saab)",
    "category": "Tiles",
    "subcategory": "Designer Collection",
    "description_en": "Elie Saab Surface — Liquid Metal Black Concrete, large-format porcelain 60x120 cm",
    "unit": "sqm",
    "price_aed": 233,
    "vendor": "RAK Ceramics",
    "in_stock": true
  },
  {
    "id": "6dcd377f-77c4-4c73-8bf3-806b3c777552",
    "sku": "RAK-ES-01-LIQUIDME-120X240",
    "brand": "RAK Ceramics (Elie Saab)",
    "category": "Tiles",
    "subcategory": "Designer Collection",
    "description_en": "Elie Saab Surface — Liquid Metal Black Concrete, large-format porcelain 120x240 cm",
    "unit": "sqm",
    "price_aed": 433,
    "vendor": "RAK Ceramics",
    "in_stock": true
  },
  {
    "id": "c2438f1a-e0a4-4555-b52a-3def07380a27",
    "sku": "DH-TIL-1401",
    "brand": "Indian Milano",
    "category": "Tiles",
    "subcategory": "Wood-effect Floor",
    "description_en": "Indian Milano Wooden Floor Tile Aston Silver Matt, 20X120 cm",
    "unit": "sqm",
    "price_aed": 48,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "0b507984-61e9-4bf8-88e4-40ee2ba0412d",
    "sku": "DH-TIL-1402",
    "brand": "Indian Milano",
    "category": "Tiles",
    "subcategory": "Wood-effect Floor",
    "description_en": "Indian Milano Wooden Floor Tile Aston Beige Matt, 20X120 cm",
    "unit": "sqm",
    "price_aed": 52,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "d31b4e81-a93c-41a8-9086-8f0f17681051",
    "sku": "DH-TIL-1406",
    "brand": "Indian Milano",
    "category": "Tiles",
    "subcategory": "Ceramic Floor",
    "description_en": "Indian Milano Ceramic Floor Tile Terrazzo Crema F Matt, 30X30 cm",
    "unit": "sqm",
    "price_aed": 24,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "e083d72f-eec2-4c2d-ab9c-be59d61a0a69",
    "sku": "DH-TIL-1407",
    "brand": "Indian Milano",
    "category": "Tiles",
    "subcategory": "Ceramic Floor",
    "description_en": "Indian Milano Ceramic Floor Tile Terrazzo Grigio Matt, 30X30 cm",
    "unit": "sqm",
    "price_aed": 26,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "e8413e92-40b1-4d2c-a774-da4783c42501",
    "sku": "DH-TIL-1408",
    "brand": "Indian Milano",
    "category": "Tiles",
    "subcategory": "Wall Tile",
    "description_en": "Indian Milano Ceramic Wall Tile Paros Decor Glossy, 30X60 cm",
    "unit": "sqm",
    "price_aed": 35,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "ec55efa5-2755-43ea-9088-dcb14f188973",
    "sku": "DH-TIL-1409",
    "brand": "Indian Milano",
    "category": "Tiles",
    "subcategory": "Wall Tile",
    "description_en": "Indian Milano Ceramic Wall Tile Absolute Bianco Glossy, 30X90 cm",
    "unit": "sqm",
    "price_aed": 38,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "f79aa503-7dfc-41f9-8fb7-4c53bbce6851",
    "sku": "DH-TIL-1411",
    "brand": "Argenta",
    "category": "Tiles",
    "subcategory": "Marble-effect Floor",
    "description_en": "Spain Marble Look Calacatta Polished, 60X60 cm",
    "unit": "sqm",
    "price_aed": 79,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "1ec23422-d5a2-4043-8088-bae27f2436d1",
    "sku": "DH-TIL-1412",
    "brand": "Argenta",
    "category": "Tiles",
    "subcategory": "Marble-effect Floor",
    "description_en": "Spain Marble Look Statuario Polished, 60X120 cm",
    "unit": "sqm",
    "price_aed": 129,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "057ea410-0500-4add-bd2a-c02c1e001f5d",
    "sku": "DH-TIL-1415",
    "brand": "Indian Milano",
    "category": "Tiles",
    "subcategory": "Outdoor Floor",
    "description_en": "Indian Milano Outdoor Tile Stone Effect Beige, 60X60 cm",
    "unit": "sqm",
    "price_aed": 65,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "3bd9bf70-4c3f-4e83-bca6-1ca9ba034b2b",
    "sku": "DH-TIL-1416",
    "brand": "Indian Milano",
    "category": "Tiles",
    "subcategory": "Outdoor Floor",
    "description_en": "Indian Milano Outdoor Tile Stone Effect Grey, 60X60 cm",
    "unit": "sqm",
    "price_aed": 65,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "5e284b1b-a237-4ba5-a273-f1472e3433b9",
    "sku": "DH-TIL-1417",
    "brand": "Argenta",
    "category": "Tiles",
    "subcategory": "Concrete-effect Floor",
    "description_en": "Spain Argenta Porcelain Concrete Effect Grigio, 60X60 cm",
    "unit": "sqm",
    "price_aed": 89,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "0debed17-6d62-43a3-ae81-b23a05b8dc45",
    "sku": "DH-TIL-1418",
    "brand": "Argenta",
    "category": "Tiles",
    "subcategory": "Concrete-effect Floor",
    "description_en": "Spain Argenta Porcelain Concrete Effect Bianco, 60X120 cm",
    "unit": "sqm",
    "price_aed": 145,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "568f5a01-aa4d-4b42-822f-0a497aae7715",
    "sku": "DH-TIL-1419",
    "brand": "Indian Milano",
    "category": "Tiles",
    "subcategory": "Mosaic",
    "description_en": "Indian Milano Mosaic Tile Hex White, 30X30 cm",
    "unit": "sqm",
    "price_aed": 49,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "a9babec5-0fbc-4516-b5f1-5ab9122241ed",
    "sku": "DH-TIL-1420",
    "brand": "Indian Milano",
    "category": "Tiles",
    "subcategory": "Mosaic",
    "description_en": "Indian Milano Mosaic Tile Hex Black, 30X30 cm",
    "unit": "sqm",
    "price_aed": 49,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "d09098cf-b558-46ba-a49d-9816b44bf0ac",
    "sku": "DH-TIL-1421",
    "brand": "Indian Milano",
    "category": "Tiles",
    "subcategory": "Parquet Flooring",
    "description_en": "Indian Milano Parquet Wood Floor Oak Light, Plank cm",
    "unit": "pcs",
    "price_aed": 89,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "4b134b0b-1a02-4125-b126-8e7e771e281f",
    "sku": "DH-TIL-1422",
    "brand": "Indian Milano",
    "category": "Tiles",
    "subcategory": "Parquet Flooring",
    "description_en": "Indian Milano Parquet Wood Floor Walnut Dark, Plank cm",
    "unit": "pcs",
    "price_aed": 95,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "6e8a36bc-3b93-4ecc-b4ce-1c20d62302db",
    "sku": "DH-TIL-1425",
    "brand": "Indian Milano",
    "category": "Tiles",
    "subcategory": "Skirting",
    "description_en": "Indian Milano Skirting Tile Matt White, 8X60 cm",
    "unit": "sqm",
    "price_aed": 18,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "904cb651-3944-44da-ad29-4c8600325bb2",
    "sku": "RAK-WB-KR0101",
    "brand": "RAK Ceramics",
    "category": "Sanitaryware",
    "subcategory": "Wash Basin",
    "description_en": "Countertop Washbasin, vitreous china, white",
    "unit": "pcs",
    "price_aed": 649,
    "vendor": "RAK Ceramics",
    "in_stock": true
  },
  {
    "id": "dc899dab-f1d2-472b-9c6d-279b603959f7",
    "sku": "RAK-WB-OC07AA",
    "brand": "RAK Ceramics",
    "category": "Sanitaryware",
    "subcategory": "Wash Basin",
    "description_en": "Countertop Washbasin Oval, vitreous china, white",
    "unit": "pcs",
    "price_aed": 949,
    "vendor": "RAK Ceramics",
    "in_stock": true
  },
  {
    "id": "51e3b450-1ba5-4312-86d9-15bc34d248e4",
    "sku": "RAK-WC-1101",
    "brand": "RAK Ceramics",
    "category": "Sanitaryware",
    "subcategory": "Water Closet",
    "description_en": "Compact Wall-hung WC, water-saving 4.5/3L dual flush, white",
    "unit": "pcs",
    "price_aed": 1399,
    "vendor": "RAK Ceramics",
    "in_stock": true
  },
  {
    "id": "85745d8f-de11-4877-9db3-9ce16af8603f",
    "sku": "RAK-WC-1102",
    "brand": "RAK Ceramics",
    "category": "Sanitaryware",
    "subcategory": "Water Closet",
    "description_en": "Wall-hung WC Rimless, water-saving 4.5/3L dual flush, white",
    "unit": "pcs",
    "price_aed": 1599,
    "vendor": "RAK Ceramics",
    "in_stock": true
  },
  {
    "id": "c18aed30-4a32-4ad9-b0a3-249382032e15",
    "sku": "RAK-ES-FB01",
    "brand": "RAK Ceramics (Elie Saab)",
    "category": "Sanitaryware",
    "subcategory": "Designer Free-standing Basin",
    "description_en": "Elie Saab Free-Standing Basin Carrara",
    "unit": "pcs",
    "price_aed": 3599,
    "vendor": "RAK Ceramics",
    "in_stock": true
  },
  {
    "id": "af9e8b5b-7b0c-41bc-96dc-fbc21c95d4fc",
    "sku": "RAK-ES-FB02",
    "brand": "RAK Ceramics (Elie Saab)",
    "category": "Sanitaryware",
    "subcategory": "Designer Free-standing Basin",
    "description_en": "Elie Saab Free-Standing Basin Calacatta",
    "unit": "pcs",
    "price_aed": 3199,
    "vendor": "RAK Ceramics",
    "in_stock": true
  },
  {
    "id": "3f380168-91da-49cc-bb60-6cba2e4d536b",
    "sku": "DH-WC-1501",
    "brand": "Danube",
    "category": "Sanitaryware",
    "subcategory": "Wall-Hung",
    "description_en": "Wall Hung WC Model 2057",
    "unit": "pcs",
    "price_aed": 320,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "33a11ec7-f14e-4e8b-b2e9-74fe361164de",
    "sku": "DH-WC-1502",
    "brand": "Milano",
    "category": "Sanitaryware",
    "subcategory": "Wall-Hung",
    "description_en": "Milano Wall Hung WC Mira",
    "unit": "pcs",
    "price_aed": 449,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "4e25ecc0-5d6c-4ffa-b44a-1b82392a73ad",
    "sku": "DH-WC-1505",
    "brand": "Milano",
    "category": "Sanitaryware",
    "subcategory": "S-Trap",
    "description_en": "Milano Marina WC with Tank S-trap",
    "unit": "pcs",
    "price_aed": 749,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "6da8eeed-dfe3-49ae-a8ea-013439f0ef1f",
    "sku": "DH-WC-1506",
    "brand": "Milano",
    "category": "Sanitaryware",
    "subcategory": "S-Trap",
    "description_en": "Milano S-Trap Two Piece WC Round",
    "unit": "pcs",
    "price_aed": 549,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "fd334ff0-a0f1-44f9-ac19-d1e6023bf803",
    "sku": "DH-WC-1509",
    "brand": "Milano",
    "category": "Sanitaryware",
    "subcategory": "P-Trap",
    "description_en": "Milano P-Trap WC Standard",
    "unit": "pcs",
    "price_aed": 549,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "ebf70cd0-9b43-4d98-bca8-4fb9bda709f1",
    "sku": "DH-WC-1510",
    "brand": "Milano",
    "category": "Sanitaryware",
    "subcategory": "P-Trap",
    "description_en": "Milano P-Trap WC Rimless",
    "unit": "pcs",
    "price_aed": 699,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "9358a971-1973-49e2-a7ad-7613b82c1192",
    "sku": "DH-WC-1512",
    "brand": "Milano",
    "category": "Sanitaryware",
    "subcategory": "Asian WC",
    "description_en": "Milano Asian WC Squat Pan",
    "unit": "pcs",
    "price_aed": 199,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "bf6e7e72-42ef-4b6e-991f-6c34b664eae2",
    "sku": "DH-WC-1514",
    "brand": "Milano",
    "category": "Sanitaryware",
    "subcategory": "Wall-Hung Set",
    "description_en": "Milano Premium WC Set with Concealed Cistern",
    "unit": "pcs",
    "price_aed": 1199,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "ac1f69ba-5b44-4a50-9f8e-35e18fed926e",
    "sku": "DH-WC-1515",
    "brand": "Milano",
    "category": "Sanitaryware",
    "subcategory": "Smart WC",
    "description_en": "Milano Smart WC Bidet Function",
    "unit": "pcs",
    "price_aed": 2999,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "8e48a74d-359c-423a-9060-062895916a7f",
    "sku": "GEB-111300005",
    "brand": "Geberit",
    "category": "Sanitaryware",
    "subcategory": "Concealed Cistern / Frame",
    "description_en": "Geberit Duofix Element Wall-hung WC 112cm w Sigma 12cm Cistern",
    "unit": "pcs",
    "price_aed": 1495,
    "vendor": "Sanipex Group (Geberit UAE)",
    "in_stock": true
  },
  {
    "id": "5f7f28a4-d192-4a6e-bde1-4335ebb458b4",
    "sku": "GEB-111796001",
    "brand": "Geberit",
    "category": "Sanitaryware",
    "subcategory": "Concealed Cistern / Frame",
    "description_en": "Geberit Duofix Element Wall-hung WC 112cm w Sigma 8cm Cistern",
    "unit": "pcs",
    "price_aed": 1395,
    "vendor": "Sanipex Group (Geberit UAE)",
    "in_stock": true
  },
  {
    "id": "eb17e350-e56a-4806-b4e2-6894b987c4bf",
    "sku": "RAK-KLD-RAK11002",
    "brand": "KLUDI RAK",
    "category": "Faucets & Mixers",
    "subcategory": "PROJECT Range",
    "description_en": "KLUDI RAK PROJECT — Single lever bath & shower mixer",
    "unit": "pcs",
    "price_aed": 750,
    "vendor": "RAK Ceramics",
    "in_stock": true
  },
  {
    "id": "d1aca329-5db8-4168-b8f9-d3c932c81842",
    "sku": "RAK-KLD-RAK11005",
    "brand": "KLUDI RAK",
    "category": "Faucets & Mixers",
    "subcategory": "PROJECT Range",
    "description_en": "KLUDI RAK PROJECT — Single lever shower mixer",
    "unit": "pcs",
    "price_aed": 590,
    "vendor": "RAK Ceramics",
    "in_stock": true
  },
  {
    "id": "3545db1d-d530-4e4e-91fa-76e258647df0",
    "sku": "RAK-KLD-RAK10028",
    "brand": "KLUDI RAK",
    "category": "Faucets & Mixers",
    "subcategory": "POLARIS Range",
    "description_en": "KLUDI RAK POLARIS — Wall-mounted single lever sink mixer",
    "unit": "pcs",
    "price_aed": 695,
    "vendor": "RAK Ceramics",
    "in_stock": true
  },
  {
    "id": "dc95600e-c3ff-43e6-b6f4-222161783407",
    "sku": "RAK-KLD-RAK13001",
    "brand": "KLUDI RAK",
    "category": "Faucets & Mixers",
    "subcategory": "POLARIS Range",
    "description_en": "KLUDI RAK POLARIS — Single lever bidet mixer",
    "unit": "pcs",
    "price_aed": 645,
    "vendor": "RAK Ceramics",
    "in_stock": true
  },
  {
    "id": "2ff42f50-c919-4ed4-b5da-38c5132f8040",
    "sku": "RAK-KLD-525900575",
    "brand": "KLUDI RAK",
    "category": "Faucets & Mixers",
    "subcategory": "KLUDI BALANCE Range",
    "description_en": "KLUDI RAK KLUDI BALANCE — Bath & shower mixer floor-standing for freestanding tub",
    "unit": "pcs",
    "price_aed": 5950,
    "vendor": "RAK Ceramics",
    "in_stock": true
  },
  {
    "id": "2d6b2b72-d831-49c0-83c7-7f27c419200f",
    "sku": "RAK-KLD-526500575",
    "brand": "KLUDI RAK",
    "category": "Faucets & Mixers",
    "subcategory": "KLUDI BALANCE Range",
    "description_en": "KLUDI RAK KLUDI BALANCE — Concealed bath/shower mixer trim set",
    "unit": "pcs",
    "price_aed": 1849,
    "vendor": "RAK Ceramics",
    "in_stock": true
  },
  {
    "id": "260a1e44-87ed-47e7-8260-c9bf23ceae1d",
    "sku": "RAK-KLD-535900575",
    "brand": "KLUDI RAK",
    "category": "Faucets & Mixers",
    "subcategory": "KLUDI AMBA Range",
    "description_en": "KLUDI RAK KLUDI AMBA — Bath & shower mixer floor-standing",
    "unit": "pcs",
    "price_aed": 5499,
    "vendor": "RAK Ceramics",
    "in_stock": true
  },
  {
    "id": "c0a95fc3-e48a-46b0-b101-8f2ea68e00de",
    "sku": "RAK-KLD-RAK16003-BK1",
    "brand": "KLUDI RAK",
    "category": "Faucets & Mixers",
    "subcategory": "SWING Range",
    "description_en": "KLUDI RAK SWING — Single lever shower mixer PVD black",
    "unit": "pcs",
    "price_aed": 1095,
    "vendor": "RAK Ceramics",
    "in_stock": true
  },
  {
    "id": "373d62f8-098a-4e66-b320-3668517ee8ca",
    "sku": "RAK-KLD-RAK14001",
    "brand": "KLUDI RAK",
    "category": "Faucets & Mixers",
    "subcategory": "SWING Range",
    "description_en": "KLUDI RAK SWING — Single lever basin mixer chrome",
    "unit": "pcs",
    "price_aed": 825,
    "vendor": "RAK Ceramics",
    "in_stock": true
  },
  {
    "id": "a6d42c21-df79-4176-8519-e3271539351a",
    "sku": "RAK-KLD-6764005-00",
    "brand": "KLUDI RAK",
    "category": "Faucets & Mixers",
    "subcategory": "KLUDI FIZZ Range",
    "description_en": "KLUDI RAK KLUDI FIZZ — Shower set 1S DN15",
    "unit": "pcs",
    "price_aed": 449,
    "vendor": "RAK Ceramics",
    "in_stock": true
  },
  {
    "id": "84fcc6fb-3782-4d3c-98aa-12870c6216b6",
    "sku": "RAK-KLD-6442505-00",
    "brand": "KLUDI RAK",
    "category": "Faucets & Mixers",
    "subcategory": "KLUDI A-QA Range",
    "description_en": "KLUDI RAK KLUDI A-QA — Head shower 1S 250 mm DN15",
    "unit": "pcs",
    "price_aed": 525,
    "vendor": "RAK Ceramics",
    "in_stock": true
  },
  {
    "id": "3532585f-9c0b-40a4-977b-544e9e27548a",
    "sku": "DH-MIX-200214",
    "brand": "Milano",
    "category": "Faucets & Mixers",
    "subcategory": "Basin Mixer",
    "description_en": "Milano Queen Basin Mixer with pop-up waste & flexible pipe, brass body, chrome finish",
    "unit": "pcs",
    "price_aed": 165,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "71eb405e-d6f4-423c-87b5-fab3f94c5fa8",
    "sku": "DH-MIX-200659",
    "brand": "Milano",
    "category": "Faucets & Mixers",
    "subcategory": "Basin Mixer",
    "description_en": "Milano Lemo Basin Mixer Matt Black with pop-up waste & flexible pipe, brass body, chrome finish",
    "unit": "pcs",
    "price_aed": 219,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "bcc6fd1a-2c4f-4bb4-be01-e6efc6b7b5b6",
    "sku": "DH-MIX-100200",
    "brand": "Milano",
    "category": "Faucets & Mixers",
    "subcategory": "Bath/Shower Mixer",
    "description_en": "Milano Aliz Bath Shower Mixer with Hand Shower with pop-up waste & flexible pipe, brass body, chrome finish",
    "unit": "pcs",
    "price_aed": 219,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "049e49a1-b61b-4742-a607-12c02c97bc82",
    "sku": "DH-MIX-100340",
    "brand": "Milano",
    "category": "Faucets & Mixers",
    "subcategory": "Bath/Shower Mixer",
    "description_en": "Milano Yana Bath Shower Mixer with pop-up waste & flexible pipe, brass body, chrome finish",
    "unit": "pcs",
    "price_aed": 299,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "e849127c-46e8-4e78-8a04-484b82b1cfa6",
    "sku": "DH-MIX-200812",
    "brand": "Milano",
    "category": "Faucets & Mixers",
    "subcategory": "Tall Basin Mixer",
    "description_en": "Milano Tall Basin Mixer Black with pop-up waste & flexible pipe, brass body, chrome finish",
    "unit": "pcs",
    "price_aed": 269,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "b8b1b5d2-89f9-4969-8f7b-ab593a264b08",
    "sku": "DH-MIX-200900",
    "brand": "Milano",
    "category": "Faucets & Mixers",
    "subcategory": "Wall Mixer",
    "description_en": "Milano Wall Mounted Basin Mixer with pop-up waste & flexible pipe, brass body, chrome finish",
    "unit": "pcs",
    "price_aed": 299,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "be7f265e-4261-44a4-a835-72bf57ba25ea",
    "sku": "DH-MIX-100777",
    "brand": "Milano",
    "category": "Faucets & Mixers",
    "subcategory": "Concealed Shower Mixer",
    "description_en": "Milano Concealed Shower Mixer 2-Way with pop-up waste & flexible pipe, brass body, chrome finish",
    "unit": "pcs",
    "price_aed": 449,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "3d82ad2b-0270-47ee-a59e-91b4cd763247",
    "sku": "DH-MIX-100778",
    "brand": "Milano",
    "category": "Faucets & Mixers",
    "subcategory": "Concealed Shower Mixer",
    "description_en": "Milano Concealed Shower Mixer 3-Way with pop-up waste & flexible pipe, brass body, chrome finish",
    "unit": "pcs",
    "price_aed": 549,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "777642f0-9681-4137-a82c-b3dafb5076ef",
    "sku": "DH-MIX-300120",
    "brand": "Milano",
    "category": "Faucets & Mixers",
    "subcategory": "Kitchen Mixer",
    "description_en": "Milano Sink Mixer Kitchen Pull Out with pop-up waste & flexible pipe, brass body, chrome finish",
    "unit": "pcs",
    "price_aed": 349,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "17b8fb05-1495-43b8-be09-6cca5571ea21",
    "sku": "DH-MIX-300121",
    "brand": "Milano",
    "category": "Faucets & Mixers",
    "subcategory": "Kitchen Mixer",
    "description_en": "Milano Sink Mixer Kitchen Single Lever with pop-up waste & flexible pipe, brass body, chrome finish",
    "unit": "pcs",
    "price_aed": 219,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "0f7d7f97-5a60-4726-8466-3ac671dbed42",
    "sku": "DH-MIX-400055",
    "brand": "Milano",
    "category": "Faucets & Mixers",
    "subcategory": "Bidet Mixer",
    "description_en": "Milano Bidet Mixer Chrome with pop-up waste & flexible pipe, brass body, chrome finish",
    "unit": "pcs",
    "price_aed": 199,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "585a8aed-638b-45ca-a3c8-9343364dca72",
    "sku": "DH-MIX-100888",
    "brand": "Milano",
    "category": "Faucets & Mixers",
    "subcategory": "Shower Mixer",
    "description_en": "Milano Shower Mixer Single Lever Wall with pop-up waste & flexible pipe, brass body, chrome finish",
    "unit": "pcs",
    "price_aed": 229,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "5481ceaa-c850-4300-b92d-44be48827e86",
    "sku": "DH-MIX-100999",
    "brand": "Milano",
    "category": "Faucets & Mixers",
    "subcategory": "Thermostatic Mixer",
    "description_en": "Milano Thermostatic Shower Mixer with pop-up waste & flexible pipe, brass body, chrome finish",
    "unit": "pcs",
    "price_aed": 599,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "5d16dfd5-3692-4867-b7e4-6b17864c9380",
    "sku": "IKEA-LGT-MELODI-005",
    "brand": "IKEA",
    "category": "Lighting",
    "subcategory": "Pendant",
    "description_en": "MELODI Pendant lamp white 28cm",
    "unit": "pcs",
    "price_aed": 49,
    "vendor": "IKEA UAE",
    "in_stock": true
  },
  {
    "id": "317092b3-a7d9-4a17-a9a3-cc1cad268af2",
    "sku": "IKEA-LGT-MELODI-006",
    "brand": "IKEA",
    "category": "Lighting",
    "subcategory": "Pendant",
    "description_en": "MELODI Pendant lamp black 28cm",
    "unit": "pcs",
    "price_aed": 49,
    "vendor": "IKEA UAE",
    "in_stock": true
  },
  {
    "id": "13d7df6b-5667-4f97-8621-990c274468d4",
    "sku": "IKEA-LGT-STORUM-010",
    "brand": "IKEA",
    "category": "Lighting",
    "subcategory": "Wall/Bulb",
    "description_en": "STORUMAN LED ceiling lamp 31cm",
    "unit": "pcs",
    "price_aed": 89,
    "vendor": "IKEA UAE",
    "in_stock": true
  },
  {
    "id": "10f8ca6a-0f7f-4088-9eb1-b83f001c5e47",
    "sku": "IKEA-LGT-FORSÅ-015",
    "brand": "IKEA",
    "category": "Lighting",
    "subcategory": "Wall/Bulb",
    "description_en": "FORSÅ Work lamp nickel-plated",
    "unit": "pcs",
    "price_aed": 95,
    "vendor": "IKEA UAE",
    "in_stock": true
  },
  {
    "id": "d226e953-f497-4630-b017-38fd17eecf86",
    "sku": "IKEA-LGT-NYMÅNE-011",
    "brand": "IKEA",
    "category": "Lighting",
    "subcategory": "Ceiling",
    "description_en": "NYMÅNE Ceiling lamp white 28cm",
    "unit": "pcs",
    "price_aed": 65,
    "vendor": "IKEA UAE",
    "in_stock": true
  },
  {
    "id": "ed3d8c86-e6dc-4c89-9098-4d5e859add05",
    "sku": "IKEA-LGT-NYMÅNE-012",
    "brand": "IKEA",
    "category": "Lighting",
    "subcategory": "Ceiling",
    "description_en": "NYMÅNE Ceiling lamp 36cm",
    "unit": "pcs",
    "price_aed": 95,
    "vendor": "IKEA UAE",
    "in_stock": true
  },
  {
    "id": "1052b2cd-3f39-4bd2-a789-fb190f3c5a82",
    "sku": "IKEA-LGT-ARSTID-013",
    "brand": "IKEA",
    "category": "Lighting",
    "subcategory": "Table/Floor",
    "description_en": "ARSTID Table lamp nickel-plated white",
    "unit": "pcs",
    "price_aed": 145,
    "vendor": "IKEA UAE",
    "in_stock": true
  },
  {
    "id": "ea8615da-0652-45b8-9cf8-7d45af391f0f",
    "sku": "IKEA-LGT-BAROME-014",
    "brand": "IKEA",
    "category": "Lighting",
    "subcategory": "Table/Floor",
    "description_en": "BAROMETER Table lamp brass white",
    "unit": "pcs",
    "price_aed": 195,
    "vendor": "IKEA UAE",
    "in_stock": true
  },
  {
    "id": "974a0aca-6871-4842-9e4b-108162bc00dc",
    "sku": "DH-VAN-1701",
    "brand": "Milano",
    "category": "Bathroom Furniture",
    "subcategory": "Vanity",
    "description_en": "Milano Plus Priya Vanity Unit with Seamless Basin 100x50",
    "unit": "pcs",
    "price_aed": 1599,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "99937a79-9ab1-44c6-ba5a-9d0259106917",
    "sku": "DH-VAN-1702",
    "brand": "Milano",
    "category": "Bathroom Furniture",
    "subcategory": "Vanity",
    "description_en": "Milano Plus Priya Vanity Unit with Seamless Basin 80x50",
    "unit": "pcs",
    "price_aed": 1299,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "ae163c33-8326-4511-916c-45f5a3738186",
    "sku": "DH-TUB-1801",
    "brand": "Milano",
    "category": "Bathware",
    "subcategory": "Bathtub",
    "description_en": "Milano Terry Freestanding Bathtub 170x80x58",
    "unit": "pcs",
    "price_aed": 3599,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "1070b4f5-7373-4bce-b3e9-2da5bc81c919",
    "sku": "DH-TUB-1802",
    "brand": "Milano",
    "category": "Bathware",
    "subcategory": "Bathtub",
    "description_en": "Milano Free Standing Bathtub Oval 170x75 White",
    "unit": "pcs",
    "price_aed": 2999,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "43ec2370-9257-4cb4-9562-aab56893ee7f",
    "sku": "DH-SHW-1901",
    "brand": "Milano",
    "category": "Bathware",
    "subcategory": "Shower Enclosure",
    "description_en": "Milano Shower Enclosure TS6223 Plus 890x890x1865",
    "unit": "pcs",
    "price_aed": 899,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "e7ebcdc5-3800-4b67-b142-8f2f30760998",
    "sku": "DH-SHW-1902",
    "brand": "Milano",
    "category": "Bathware",
    "subcategory": "Shower Enclosure",
    "description_en": "Milano Shower Cubicle BB-4C Quadrant 900x900x1950 Chrome",
    "unit": "pcs",
    "price_aed": 599,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "1e8aa7aa-859f-458f-bbd6-d2ff05268524",
    "sku": "DH-ACC-2001",
    "brand": "Milano",
    "category": "Bathroom Accessories",
    "subcategory": "Rain Shower",
    "description_en": "Milano Rain Shower Head 300mm Chrome",
    "unit": "pcs",
    "price_aed": 249,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "35eb5305-7130-40b8-9b34-550a0c457e45",
    "sku": "DH-ACC-2002",
    "brand": "Milano",
    "category": "Bathroom Accessories",
    "subcategory": "Rain Shower",
    "description_en": "Milano Rain Shower Head 400mm Chrome",
    "unit": "pcs",
    "price_aed": 349,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "da0f0afc-0a4a-4c29-a3a6-f2a4c4a12da4",
    "sku": "DH-ACC-2003",
    "brand": "Milano",
    "category": "Bathroom Accessories",
    "subcategory": "Floor Drain",
    "description_en": "Milano Floor Drain Stainless Steel 100x100",
    "unit": "pcs",
    "price_aed": 49,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "741490f9-4599-49c2-9869-e34026d4fc00",
    "sku": "DH-ACC-2004",
    "brand": "Milano",
    "category": "Bathroom Accessories",
    "subcategory": "Bath Accessories",
    "description_en": "Milano Bath Accessory Set 6-pcs Chrome",
    "unit": "pcs",
    "price_aed": 199,
    "vendor": "Danube Home",
    "in_stock": true
  },
  {
    "id": "a598ce9e-191b-4ff9-9f6f-996ecae36a3e",
    "sku": "IKEA-METOD/MAXIMERA-59459181",
    "brand": "IKEA",
    "category": "Kitchen",
    "subcategory": "Cabinet/Front",
    "description_en": "METOD/MAXIMERA Hi cab w 2 doors/4 drawers white/Bodbyn off-white 60x60x200",
    "unit": "pcs",
    "price_aed": 2495,
    "vendor": "IKEA UAE",
    "in_stock": true
  },
  {
    "id": "21504ddc-2bdd-4c1a-9642-e85e88eb9858",
    "sku": "IKEA-METOD/MAXIMERA-69507006",
    "brand": "IKEA",
    "category": "Kitchen",
    "subcategory": "Cabinet/Front",
    "description_en": "METOD/MAXIMERA Base cabinet w drawer/door white/Vallstena 60x37",
    "unit": "pcs",
    "price_aed": 945,
    "vendor": "IKEA UAE",
    "in_stock": true
  },
  {
    "id": "5163d524-05e5-4ee6-acf2-7c95f4db8fab",
    "sku": "IKEA-STR-PAX-001",
    "brand": "IKEA",
    "category": "Storage",
    "subcategory": "PAX",
    "description_en": "PAX Wardrobe frame white 100x58x236",
    "unit": "pcs",
    "price_aed": 595,
    "vendor": "IKEA UAE",
    "in_stock": true
  },
  {
    "id": "20e83aae-119c-4a5e-b013-95208bd3ba55",
    "sku": "IKEA-STR-PAX-002",
    "brand": "IKEA",
    "category": "Storage",
    "subcategory": "PAX",
    "description_en": "PAX Wardrobe frame white 75x58x236",
    "unit": "pcs",
    "price_aed": 495,
    "vendor": "IKEA UAE",
    "in_stock": true
  },
  {
    "id": "56531a7b-4846-4fac-8e69-082114358da5",
    "sku": "IKEA-STR-KOMPLE-009",
    "brand": "IKEA",
    "category": "Storage",
    "subcategory": "KOMPLEMENT",
    "description_en": "KOMPLEMENT Shelf white 100x58",
    "unit": "pcs",
    "price_aed": 65,
    "vendor": "IKEA UAE",
    "in_stock": true
  },
  {
    "id": "2310cd74-5639-45b8-8f02-0008a93bf1d7",
    "sku": "IKEA-STR-KOMPLE-010",
    "brand": "IKEA",
    "category": "Storage",
    "subcategory": "KOMPLEMENT",
    "description_en": "KOMPLEMENT Shelf white 75x58",
    "unit": "pcs",
    "price_aed": 55,
    "vendor": "IKEA UAE",
    "in_stock": true
  },
  {
    "id": "f3444e90-290d-4a98-bf45-8f0b8b9f2100",
    "sku": "IKEA-STR-EKET-017",
    "brand": "IKEA",
    "category": "Storage",
    "subcategory": "EKET",
    "description_en": "EKET Cabinet w 2 doors and 1 shelf dark grey 70x35x70",
    "unit": "pcs",
    "price_aed": 295,
    "vendor": "IKEA UAE",
    "in_stock": true
  },
  {
    "id": "e1820863-c119-4e53-8d5e-ec8b0a1bff4f",
    "sku": "IKEA-STR-EKET-018",
    "brand": "IKEA",
    "category": "Storage",
    "subcategory": "EKET",
    "description_en": "EKET Cabinet w 4 compartments white 70x35x70",
    "unit": "pcs",
    "price_aed": 245,
    "vendor": "IKEA UAE",
    "in_stock": true
  },
  {
    "id": "d576071c-7f29-419c-936b-44124b604e92",
    "sku": "IKEA-STR-IDÅSEN-021",
    "brand": "IKEA",
    "category": "Storage",
    "subcategory": "IDÅSEN",
    "description_en": "IDÅSEN Cabinet w doors and drawers dark green 80x47x119",
    "unit": "pcs",
    "price_aed": 1195,
    "vendor": "IKEA UAE",
    "in_stock": true
  },
  {
    "id": "95b3d381-1c7f-4ef7-ba13-c2e61cd9aa83",
    "sku": "IKEA-STR-IDÅSEN-022",
    "brand": "IKEA",
    "category": "Storage",
    "subcategory": "IDÅSEN",
    "description_en": "IDÅSEN Cabinet w doors black 80x47x119",
    "unit": "pcs",
    "price_aed": 1195,
    "vendor": "IKEA UAE",
    "in_stock": true
  },
  {
    "id": "7862c6dc-0865-4f1b-acb4-a92552596e2a",
    "sku": "IKEA-STR-KALLAX-023",
    "brand": "IKEA",
    "category": "Storage",
    "subcategory": "KALLAX",
    "description_en": "KALLAX Shelving unit white 77x77",
    "unit": "pcs",
    "price_aed": 245,
    "vendor": "IKEA UAE",
    "in_stock": true
  },
  {
    "id": "b11af3de-4a02-4e03-b915-d14fb5b2fb0a",
    "sku": "IKEA-STR-KALLAX-024",
    "brand": "IKEA",
    "category": "Storage",
    "subcategory": "KALLAX",
    "description_en": "KALLAX Shelving unit white 147x77",
    "unit": "pcs",
    "price_aed": 395,
    "vendor": "IKEA UAE",
    "in_stock": true
  },
  {
    "id": "8de613d8-a4e7-4cae-820d-c2c48ea6f23c",
    "sku": "IKEA-STR-BILLY-025",
    "brand": "IKEA",
    "category": "Storage",
    "subcategory": "BILLY",
    "description_en": "BILLY Bookcase white 80x28x202",
    "unit": "pcs",
    "price_aed": 295,
    "vendor": "IKEA UAE",
    "in_stock": true
  },
  {
    "id": "2adca388-06af-4226-86e5-1082e6536d76",
    "sku": "ACE-TOL-2301240",
    "brand": "Suki",
    "category": "Tools",
    "subcategory": "Hand Tools",
    "description_en": "Suki Multi-tool Set 25pc",
    "unit": "pcs",
    "price_aed": 75,
    "vendor": "Ace Hardware UAE",
    "in_stock": true
  },
  {
    "id": "64e30f19-d32d-4bf4-a1c7-3d7e34a0f282",
    "sku": "ACE-TOL-2301241",
    "brand": "Craftsman",
    "category": "Tools",
    "subcategory": "Hand Tools",
    "description_en": "Craftsman Socket Set 1/4-inch 22pc",
    "unit": "pcs",
    "price_aed": 195,
    "vendor": "Ace Hardware UAE",
    "in_stock": true
  },
  {
    "id": "7d61b7df-ad24-4610-bef3-8f21b9f43633",
    "sku": "ACE-TOL-2301202",
    "brand": "Black+Decker",
    "category": "Tools",
    "subcategory": "Power Tools",
    "description_en": "Black+Decker Cordless Compact 2-Gear Hammer Drill Kit 18V",
    "unit": "pcs",
    "price_aed": 549,
    "vendor": "Ace Hardware UAE",
    "in_stock": true
  },
  {
    "id": "d717b917-30b1-4b06-a131-f16b668295ea",
    "sku": "ACE-TOL-2301203",
    "brand": "Black+Decker",
    "category": "Tools",
    "subcategory": "Power Tools",
    "description_en": "Black+Decker Corded Hammer Drill 800W KR8542",
    "unit": "pcs",
    "price_aed": 295,
    "vendor": "Ace Hardware UAE",
    "in_stock": true
  },
  {
    "id": "69f54e86-f6f9-4964-9ee4-1552313eedfc",
    "sku": "IKEA-FUR-KIVIK-001",
    "brand": "IKEA",
    "category": "Furniture",
    "subcategory": "Living/Bedroom",
    "description_en": "KIVIK 3-seat sofa Hillared dark blue",
    "unit": "pcs",
    "price_aed": 3195,
    "vendor": "IKEA UAE",
    "in_stock": true
  },
  {
    "id": "ae88703a-cbe3-4e7f-9018-407bd2f1a43e",
    "sku": "IKEA-FUR-KIVIK-002",
    "brand": "IKEA",
    "category": "Furniture",
    "subcategory": "Living/Bedroom",
    "description_en": "KIVIK 2-seat sofa Hillared anthracite",
    "unit": "pcs",
    "price_aed": 2495,
    "vendor": "IKEA UAE",
    "in_stock": true
  },
  {
    "id": "1270f038-57ca-4a2b-ab90-88ca4b12b1af",
    "sku": "HC-SOFA-2201",
    "brand": "Home Centre",
    "category": "Furniture",
    "subcategory": "Sofa",
    "description_en": "HOME CENTRE Helios 3-Seater Fabric Sofa Grey",
    "unit": "pcs",
    "price_aed": 1499,
    "vendor": "Home Centre UAE",
    "in_stock": true
  },
  {
    "id": "d35fb1e2-2dbc-4d70-a4fd-0e7bcbdddbee",
    "sku": "HC-SOFA-2202",
    "brand": "Home Centre",
    "category": "Furniture",
    "subcategory": "Sofa",
    "description_en": "HOME CENTRE Helios 2-Seater Fabric Sofa Grey",
    "unit": "pcs",
    "price_aed": 1099,
    "vendor": "Home Centre UAE",
    "in_stock": true
  },
  {
    "id": "ae5de094-ebef-468b-99e3-07b8fff1eaba",
    "sku": "HC-DIN-2301",
    "brand": "Home Centre",
    "category": "Furniture",
    "subcategory": "Dining",
    "description_en": "HOME CENTRE Sam Bar Table Walnut",
    "unit": "pcs",
    "price_aed": 999,
    "vendor": "Home Centre UAE",
    "in_stock": true
  },
  {
    "id": "c5175505-7621-4f55-b8d5-13d20701c870",
    "sku": "HC-DIN-2302",
    "brand": "Home Centre",
    "category": "Furniture",
    "subcategory": "Dining",
    "description_en": "HOME CENTRE Mocha 6-Seater Dining Set",
    "unit": "pcs",
    "price_aed": 2999,
    "vendor": "Home Centre UAE",
    "in_stock": true
  },
  {
    "id": "9ebb03ac-638f-4965-82d0-099f03e71d97",
    "sku": "HC-LIV-2401",
    "brand": "Home Centre",
    "category": "Furniture",
    "subcategory": "Living Room",
    "description_en": "HOME CENTRE Ashland Coffee Table Walnut",
    "unit": "pcs",
    "price_aed": 1099,
    "vendor": "Home Centre UAE",
    "in_stock": true
  },
  {
    "id": "6c0e04e4-99f8-436d-8f7f-527052604070",
    "sku": "HC-LIV-2402",
    "brand": "Home Centre",
    "category": "Furniture",
    "subcategory": "Living Room",
    "description_en": "HOME CENTRE Ashland Side Table Walnut",
    "unit": "pcs",
    "price_aed": 549,
    "vendor": "Home Centre UAE",
    "in_stock": true
  },
  {
    "id": "db9c7bdf-abc9-4354-be91-66fc43e165bc",
    "sku": "HC-BED-2501",
    "brand": "Home Centre",
    "category": "Furniture",
    "subcategory": "Bedroom",
    "description_en": "HOME CENTRE Mocha Queen Bed with Storage Walnut",
    "unit": "pcs",
    "price_aed": 2499,
    "vendor": "Home Centre UAE",
    "in_stock": true
  },
  {
    "id": "e7d83815-ff04-4942-ac53-38fade1b5bc0",
    "sku": "HC-BED-2502",
    "brand": "Home Centre",
    "category": "Furniture",
    "subcategory": "Bedroom",
    "description_en": "HOME CENTRE Mocha King Bed with Storage Walnut",
    "unit": "pcs",
    "price_aed": 2999,
    "vendor": "Home Centre UAE",
    "in_stock": true
  },
  {
    "id": "00966203-e947-4b2e-b619-c2ed46585526",
    "sku": "HC-SFT-2601",
    "brand": "Home Centre",
    "category": "Soft Furnishings",
    "subcategory": "Bedding",
    "description_en": "HOME CENTRE Cotton Fitted Sheet King 200tc White",
    "unit": "pcs",
    "price_aed": 149,
    "vendor": "Home Centre UAE",
    "in_stock": true
  },
  {
    "id": "4fcaf6a3-7d8a-4502-9927-ec0a2e5c6aeb",
    "sku": "HC-SFT-2602",
    "brand": "Home Centre",
    "category": "Soft Furnishings",
    "subcategory": "Bedding",
    "description_en": "HOME CENTRE Cotton Fitted Sheet Queen 200tc White",
    "unit": "pcs",
    "price_aed": 119,
    "vendor": "Home Centre UAE",
    "in_stock": true
  },
  {
    "id": "f1095b2d-a6f3-4cbf-8dba-08eafdd27eaf",
    "sku": "HC-CSH-2701",
    "brand": "Home Centre",
    "category": "Soft Furnishings",
    "subcategory": "Cushions/Throws",
    "description_en": "HOME CENTRE Filled Cushion 45x45 Velvet Beige",
    "unit": "pcs",
    "price_aed": 79,
    "vendor": "Home Centre UAE",
    "in_stock": true
  },
  {
    "id": "fecc423b-987e-43c0-af45-cbfb541aa667",
    "sku": "HC-CSH-2702",
    "brand": "Home Centre",
    "category": "Soft Furnishings",
    "subcategory": "Cushions/Throws",
    "description_en": "HOME CENTRE Filled Cushion 45x45 Velvet Navy",
    "unit": "pcs",
    "price_aed": 79,
    "vendor": "Home Centre UAE",
    "in_stock": true
  },
  {
    "id": "37cfb933-a2ef-4b44-ac6c-936c3747a389",
    "sku": "HC-CUR-2801",
    "brand": "Home Centre",
    "category": "Soft Furnishings",
    "subcategory": "Window Treatments",
    "description_en": "HOME CENTRE Blackout Curtain 140x230 Beige",
    "unit": "pcs",
    "price_aed": 199,
    "vendor": "Home Centre UAE",
    "in_stock": true
  },
  {
    "id": "b2a35f7c-0de7-4e62-9024-4d8ab6863829",
    "sku": "HC-CUR-2802",
    "brand": "Home Centre",
    "category": "Soft Furnishings",
    "subcategory": "Window Treatments",
    "description_en": "HOME CENTRE Blackout Curtain 140x230 Grey",
    "unit": "pcs",
    "price_aed": 199,
    "vendor": "Home Centre UAE",
    "in_stock": true
  },
  {
    "id": "35200639-db3d-4f44-85d3-78af8894f7ae",
    "sku": "HC-DEC-2901",
    "brand": "Home Centre",
    "category": "Decor",
    "subcategory": "Home Decor",
    "description_en": "HOME CENTRE Wall Art Canvas 80x60 Abstract",
    "unit": "pcs",
    "price_aed": 299,
    "vendor": "Home Centre UAE",
    "in_stock": true
  },
  {
    "id": "03356457-a522-4046-9294-1c575eee7181",
    "sku": "HC-DEC-2902",
    "brand": "Home Centre",
    "category": "Decor",
    "subcategory": "Home Decor",
    "description_en": "HOME CENTRE Wall Mirror Round 80cm Gold",
    "unit": "pcs",
    "price_aed": 449,
    "vendor": "Home Centre UAE",
    "in_stock": true
  },
  {
    "id": "62729036-c268-4a36-8075-3dde2f07f541",
    "sku": "ACE-PNT-2298848",
    "brand": "Jotun",
    "category": "Paint & Supplies",
    "subcategory": "Paint",
    "description_en": "Jotun Acrylic Emulsion Exterior Primer 18L White",
    "unit": "pcs",
    "price_aed": 285,
    "vendor": "Ace Hardware UAE",
    "in_stock": true
  },
  {
    "id": "8114da8c-0a01-4708-a2b7-3d22249f54a9",
    "sku": "ACE-PNT-2298847",
    "brand": "Jotun",
    "category": "Paint & Supplies",
    "subcategory": "Paint",
    "description_en": "Jotun Acrylic Emulsion Exterior Primer 4L White",
    "unit": "pcs",
    "price_aed": 95,
    "vendor": "Ace Hardware UAE",
    "in_stock": true
  },
  {
    "id": "7e2c46e0-180e-4039-938c-026709806f84",
    "sku": "ACE-PNT-2055005",
    "brand": "Roller",
    "category": "Paint & Supplies",
    "subcategory": "Painting Supplies",
    "description_en": "Roller Sleeve Pack 9-inch 3pcs",
    "unit": "pcs",
    "price_aed": 35,
    "vendor": "Ace Hardware UAE",
    "in_stock": true
  },
  {
    "id": "106e3d7c-0309-4188-adc5-509d9e47e476",
    "sku": "ACE-PNT-2055006",
    "brand": "Paint",
    "category": "Paint & Supplies",
    "subcategory": "Painting Supplies",
    "description_en": "Paint Brush Set 5pcs Synthetic Bristle",
    "unit": "pcs",
    "price_aed": 45,
    "vendor": "Ace Hardware UAE",
    "in_stock": true
  },
  {
    "id": "2f7f7507-e4b3-4caa-a8af-490cfb3adaf2",
    "sku": "ACE-PLS-2060100",
    "brand": "Sika",
    "category": "Building Materials",
    "subcategory": "Adhesive",
    "description_en": "Sika Bonding Adhesive SBR 5L",
    "unit": "bag",
    "price_aed": 95,
    "vendor": "Ace Hardware UAE",
    "in_stock": true
  },
  {
    "id": "b0523c2f-20e5-4c47-aeb2-d9aacf3f012c",
    "sku": "ACE-PLS-2060101",
    "brand": "Sika",
    "category": "Building Materials",
    "subcategory": "Tile Adhesive",
    "description_en": "Sika Cementone Tile Adhesive 25kg White",
    "unit": "bag",
    "price_aed": 65,
    "vendor": "Ace Hardware UAE",
    "in_stock": true
  },
  {
    "id": "2d62caeb-488c-4c66-bce3-67d50a05a028",
    "sku": "ACE-PLS-2060110",
    "brand": "BASF",
    "category": "Building Materials",
    "subcategory": "Tile Adhesive",
    "description_en": "BASF MasterTile Adhesive 25kg",
    "unit": "bag",
    "price_aed": 75,
    "vendor": "Ace Hardware UAE",
    "in_stock": true
  },
  {
    "id": "70f9e129-a398-4ecd-b631-f034297e07d4",
    "sku": "ACE-PLS-2060102",
    "brand": "Sika",
    "category": "Building Materials",
    "subcategory": "Repair Mortar",
    "description_en": "Sika MonoTop 615 Repair Mortar 25kg",
    "unit": "bag",
    "price_aed": 145,
    "vendor": "Ace Hardware UAE",
    "in_stock": true
  },
  {
    "id": "3a5265f2-5e8d-4f0a-902f-987267e3fbff",
    "sku": "ACE-PLS-2060103",
    "brand": "Sika",
    "category": "Building Materials",
    "subcategory": "Waterproofing",
    "description_en": "Sika 1+ Waterproofing Cementitious 5kg",
    "unit": "bag",
    "price_aed": 85,
    "vendor": "Ace Hardware UAE",
    "in_stock": true
  },
  {
    "id": "6ca1ee3b-04e5-4219-a38c-c56044fbf0e7",
    "sku": "ACE-PLS-2060120",
    "brand": "ABC",
    "category": "Building Materials",
    "subcategory": "Plaster",
    "description_en": "ABC Premix Plaster 40kg",
    "unit": "bag",
    "price_aed": 35,
    "vendor": "Ace Hardware UAE",
    "in_stock": true
  },
  {
    "id": "7f3c5362-de74-4466-8ff3-b31a0eafdf4f",
    "sku": "ACE-PLS-2060121",
    "brand": "ABC",
    "category": "Building Materials",
    "subcategory": "Plaster",
    "description_en": "ABC Skim Coat Smooth Finish 25kg",
    "unit": "bag",
    "price_aed": 45,
    "vendor": "Ace Hardware UAE",
    "in_stock": true
  },
  {
    "id": "db733e3e-3639-483f-b070-29817662d8cc",
    "sku": "ACE-PLS-2060130",
    "brand": "White",
    "category": "Building Materials",
    "subcategory": "Cement",
    "description_en": "White Cement 25kg JK Cement",
    "unit": "bag",
    "price_aed": 55,
    "vendor": "Ace Hardware UAE",
    "in_stock": true
  },
  {
    "id": "4244aa71-d71b-4553-aadf-1d1094297098",
    "sku": "ACE-PLS-2060131",
    "brand": "Grey",
    "category": "Building Materials",
    "subcategory": "Cement",
    "description_en": "Grey Cement OPC 50kg Lafarge",
    "unit": "bag",
    "price_aed": 22,
    "vendor": "Ace Hardware UAE",
    "in_stock": true
  },
  {
    "id": "480e368b-797b-4d80-8da2-fef7b5d5f180",
    "sku": "ACE-PLS-2060140",
    "brand": "Sika",
    "category": "Building Materials",
    "subcategory": "Grout",
    "description_en": "Sika Grout 212 Non-shrink 25kg",
    "unit": "bag",
    "price_aed": 95,
    "vendor": "Ace Hardware UAE",
    "in_stock": true
  },
  {
    "id": "50fbe570-4f27-4dc0-acef-c7bfc6986125",
    "sku": "ACE-PLS-2060141",
    "brand": "Mapei",
    "category": "Building Materials",
    "subcategory": "Tile Grout",
    "description_en": "Mapei Ultracolor Plus Tile Grout 5kg White",
    "unit": "bag",
    "price_aed": 65,
    "vendor": "Ace Hardware UAE",
    "in_stock": true
  },
  {
    "id": "8356ba8c-49a1-4270-b383-e90789d23cc8",
    "sku": "ACE-PLS-2060142",
    "brand": "Mapei",
    "category": "Building Materials",
    "subcategory": "Tile Grout",
    "description_en": "Mapei Ultracolor Plus Tile Grout 5kg Grey",
    "unit": "bag",
    "price_aed": 65,
    "vendor": "Ace Hardware UAE",
    "in_stock": true
  },
  {
    "id": "81c67daa-44cd-45d2-ae2d-c576714bebd4",
    "sku": "ACE-PLS-2060150",
    "brand": "Sika",
    "category": "Building Materials",
    "subcategory": "Sealant",
    "description_en": "Sika Silicone Sealant 300ml Clear",
    "unit": "pcs",
    "price_aed": 35,
    "vendor": "Ace Hardware UAE",
    "in_stock": true
  },
  {
    "id": "a1a8a382-9195-4103-a6a0-ee9377be2dc7",
    "sku": "ACE-PLS-2060151",
    "brand": "Sika",
    "category": "Building Materials",
    "subcategory": "Sealant",
    "description_en": "Sika Silicone Sealant 300ml Black",
    "unit": "pcs",
    "price_aed": 35,
    "vendor": "Ace Hardware UAE",
    "in_stock": true
  },
  {
    "id": "5da68622-7dea-44cd-aedf-43f1b8c13a60",
    "sku": "ACE-FIX-2070100",
    "brand": "Diall",
    "category": "Hardware",
    "subcategory": "Fixings",
    "description_en": "Diall Zinc-Plated Concrete Screw 7.5x182mm 6pc",
    "unit": "pcs",
    "price_aed": 25,
    "vendor": "Ace Hardware UAE",
    "in_stock": true
  },
  {
    "id": "da12d210-664f-4f29-88d7-a68114cc767a",
    "sku": "ACE-FIX-2070101",
    "brand": "Diall",
    "category": "Hardware",
    "subcategory": "Fixings",
    "description_en": "Diall Nylon Frame Fixing Pack 50pc",
    "unit": "pcs",
    "price_aed": 39,
    "vendor": "Ace Hardware UAE",
    "in_stock": true
  },
  {
    "id": "baaa6102-3e10-49c7-ba75-f6ea450fe7d7",
    "sku": "HAF-31171521",
    "brand": "Hafele",
    "category": "Hardware",
    "subcategory": "Door & Cabinet Hardware",
    "description_en": "Hafele 110° Kitchen Cabinet Hinge Half Overlay 2pc",
    "unit": "pcs",
    "price_aed": 49,
    "vendor": "Hafele UAE",
    "in_stock": true
  },
  {
    "id": "04f04773-3873-404e-95f2-5c5301c8f3a6",
    "sku": "HAF-31171531",
    "brand": "Hafele",
    "category": "Hardware",
    "subcategory": "Door & Cabinet Hardware",
    "description_en": "Hafele 110° Kitchen Cabinet Hinge Full Overlay Soft-close 2pc",
    "unit": "pcs",
    "price_aed": 89,
    "vendor": "Hafele UAE",
    "in_stock": true
  },
  {
    "id": "8ae6f4ed-6d44-4be1-ae83-cff9454976c1",
    "sku": "GYP-3001",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Plasterboard",
    "description_en": "Gyproc WallBoard 12.5mm 1200x2400",
    "unit": "sqm",
    "price_aed": 35,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "af91692b-f1a9-4879-ae94-0f931e33ebd1",
    "sku": "GYP-3002",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Plasterboard",
    "description_en": "Gyproc WallBoard 9.5mm 1200x2400",
    "unit": "sqm",
    "price_aed": 28,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "20355d17-8a92-4c81-9eba-4c193403c435",
    "sku": "GYP-3004",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Fire-rated Board",
    "description_en": "Gyproc FireLine 12.5mm 1200x2400 Pink",
    "unit": "sqm",
    "price_aed": 48,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "881acdaa-91f2-4db5-9ebe-badd83928536",
    "sku": "GYP-3005",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Fire-rated Board",
    "description_en": "Gyproc FireLine 15mm 1200x2400 Pink",
    "unit": "sqm",
    "price_aed": 58,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "bb526909-573f-4ef7-ae1d-d0d123911334",
    "sku": "GYP-3006",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Acoustic Board",
    "description_en": "Gyproc SoundBloc 12.5mm 1200x2400 Blue",
    "unit": "sqm",
    "price_aed": 55,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "84803504-29f0-42bb-b8c2-42021141437e",
    "sku": "GYP-3007",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Acoustic Board",
    "description_en": "Gyproc SoundBloc 15mm 1200x2400 Blue",
    "unit": "sqm",
    "price_aed": 65,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "0dd4768f-9034-4afc-8fb0-0f60e9adc992",
    "sku": "GYP-3008",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "MR Board",
    "description_en": "Gyproc Moisture Resistant 12.5mm 1200x2400 Green",
    "unit": "sqm",
    "price_aed": 49,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "f9152836-ca60-445c-a220-2a9a52d67b50",
    "sku": "GYP-3009",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "High-Impact Board",
    "description_en": "Gyproc Habito Board 12.5mm 1200x2400 High-impact",
    "unit": "sqm",
    "price_aed": 79,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "948264a0-753f-423d-913c-42929925101c",
    "sku": "GYP-3010",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Aerated Board",
    "description_en": "Gyproc Lite RG EN 12.5mm 1200x2400",
    "unit": "sqm",
    "price_aed": 42,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "e2719e68-4488-4245-ac5b-82826fdcdbb6",
    "sku": "GYP-3011",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Exterior Board",
    "description_en": "Glasroc X Exterior Sheathing 12.5mm 1200x2400",
    "unit": "sqm",
    "price_aed": 89,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "c5d64ad3-87dd-4a07-9ace-5d9836c3238d",
    "sku": "GYP-3012",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Fireproof Board",
    "description_en": "Glasroc F Fireproof Board 15mm 1200x2400",
    "unit": "sqm",
    "price_aed": 95,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "40da0773-e51b-4005-8cb9-0918d25e49ac",
    "sku": "GYP-3013",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Suspended Ceiling Tile",
    "description_en": "Gyptone Plain Plasterboard Ceiling 600x600",
    "unit": "pcs",
    "price_aed": 22,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "08196e5e-e0e7-418d-9e6e-d7dcfc5549a8",
    "sku": "GYP-3014",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Acoustic Ceiling Tile",
    "description_en": "Gyptone Activ'Air Plain 600x600 Edge E",
    "unit": "pcs",
    "price_aed": 28,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "99f1a53f-da89-4cf7-90a7-fe4651f5caaf",
    "sku": "GYP-3015",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Perforated Acoustic Tile",
    "description_en": "Gyptone Quattro 22 Activ'Air 600x600",
    "unit": "pcs",
    "price_aed": 35,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "f89ad7e7-7920-458b-a12c-55115e77b2fb",
    "sku": "GYP-3016",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Perforated Acoustic Tile",
    "description_en": "Gyptone Sixto 60 Activ'Air 600x600",
    "unit": "pcs",
    "price_aed": 38,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "e938f863-f5d6-4b0c-8ee9-a1a8164c4edb",
    "sku": "GYP-3017",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Vinyl Ceiling Tile",
    "description_en": "Gyprex Vinyl-faced Tile 600x600 Edge A",
    "unit": "pcs",
    "price_aed": 18,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "fefc6975-5d31-4bd4-bdfd-d446bb43b9f5",
    "sku": "GYP-3018",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Vinyl Ceiling Tile",
    "description_en": "Gyprex Vinyl-faced Tile 600x1200 Edge E",
    "unit": "pcs",
    "price_aed": 32,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "342bb4f7-26e2-4787-91e0-647f01d4c2ee",
    "sku": "GYP-3019",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Perforated Seamless Board",
    "description_en": "Rigitone 8/18 Perforated Board 1200x2000",
    "unit": "pcs",
    "price_aed": 195,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "1613203e-e964-40e0-90f0-345ef7acb4fa",
    "sku": "GYP-3020",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Perforated Seamless Board",
    "description_en": "Rigitone 12/25 Perforated Board 1200x2000",
    "unit": "pcs",
    "price_aed": 195,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "d152a09e-90e8-43d7-bdb9-e37ae03134ea",
    "sku": "GYP-3021",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Ceiling Grid",
    "description_en": "Gyptone GRID Concealed Profile 3.6m",
    "unit": "pcs",
    "price_aed": 45,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "e025eb71-3571-4a32-bc53-b37839f14261",
    "sku": "GYP-3022",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Suspended Ceiling Kit",
    "description_en": "Gyproc MF Ceiling System Set 10sqm",
    "unit": "pcs",
    "price_aed": 395,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "15d20e4c-f6a4-4750-97d2-c48b35e30748",
    "sku": "GYP-3023",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Stud",
    "description_en": "Gypframe AcouStud 70mm 3.6m",
    "unit": "pcs",
    "price_aed": 28,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "d8073099-b935-431a-bbf4-7eaad5c95f46",
    "sku": "GYP-3024",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Stud",
    "description_en": "Gypframe AcouStud 92mm 3.6m",
    "unit": "pcs",
    "price_aed": 32,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "7fff46a3-5425-4213-b047-a68d2f83ba8f",
    "sku": "GYP-3026",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Channel",
    "description_en": "Gypframe Channel U-Track 70mm 3.6m",
    "unit": "pcs",
    "price_aed": 24,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "bc52ad4d-a959-4889-83a5-d7074806ba08",
    "sku": "GYP-3027",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Channel",
    "description_en": "Gypframe Channel U-Track 92mm 3.6m",
    "unit": "pcs",
    "price_aed": 28,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "1e07a877-8b3b-4f5f-b615-86efe54d2f08",
    "sku": "GYP-3028",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "T-Grid Main",
    "description_en": "Gypframe Eco T Main Runner 3.6m",
    "unit": "pcs",
    "price_aed": 22,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "64848c37-1104-44aa-becb-510ffecc4dd3",
    "sku": "GYP-3029",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "T-Grid Cross",
    "description_en": "Gypframe Eco T Cross Tee 1200mm",
    "unit": "pcs",
    "price_aed": 8,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "a1a662cc-2d08-4a7d-9f39-ee6338db308e",
    "sku": "GYP-3030",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Wall Angle",
    "description_en": "Gyproc L-Angle Wall Trim 3m",
    "unit": "pcs",
    "price_aed": 12,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "c1c02716-7285-4478-aa64-16b931506a19",
    "sku": "GYP-3031",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Drywall Screw",
    "description_en": "Gyproc Drywall Screw 25mm Box 1000pc",
    "unit": "box",
    "price_aed": 45,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "e491122b-e867-4e9f-8ccc-d24fa6711415",
    "sku": "GYP-3032",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Drywall Screw",
    "description_en": "Gyproc Drywall Screw 35mm Box 1000pc",
    "unit": "box",
    "price_aed": 55,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "4187f4d9-fc4b-4665-b1d3-d9258db620d4",
    "sku": "GYP-3033",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Self-drilling Screw",
    "description_en": "Gyproc Jack-Point Screw 13mm Box 1000pc",
    "unit": "box",
    "price_aed": 65,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "e08878d0-06b4-4eda-9dce-01f32c82a598",
    "sku": "GYP-3034",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Waferhead Screw",
    "description_en": "Gyproc Waferhead Screw 25mm Box 500pc",
    "unit": "box",
    "price_aed": 55,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "d7e8e735-45f2-403f-acfe-c010e79c2d5e",
    "sku": "GYP-3035",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Joint Tape",
    "description_en": "Gyproc Paper Joint Tape 75m roll",
    "unit": "roll",
    "price_aed": 18,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "08f47e1a-b76b-4e2e-b3a3-d5f94b569c96",
    "sku": "GYP-3036",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Mesh Tape",
    "description_en": "Gyproc Fibre Mesh Tape 90m roll",
    "unit": "roll",
    "price_aed": 22,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "02c73829-b6d7-4c10-9640-2323fa36f784",
    "sku": "GYP-3037",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Corner Tape",
    "description_en": "Gyproc Metal Corner Tape 30m roll",
    "unit": "roll",
    "price_aed": 32,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "00287d4f-da2c-4d70-8d9e-ecd2af864b6e",
    "sku": "GYP-3038",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Corner Bead",
    "description_en": "Gyproc Standard Corner Bead 3m",
    "unit": "pcs",
    "price_aed": 12,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "a679b916-0328-4344-a4ef-fbb74af46f52",
    "sku": "GYP-3039",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Joint Filler",
    "description_en": "Gyproc Joint Compound 25kg",
    "unit": "bag",
    "price_aed": 65,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "97405135-6344-44d9-9f24-58c7497e2134",
    "sku": "GYP-3040",
    "brand": "Gyproc / Saint-Gobain",
    "category": "Drywall & Ceilings",
    "subcategory": "Tape",
    "description_en": "Glasroc X Tape 50m roll",
    "unit": "roll",
    "price_aed": 35,
    "vendor": "Saint-Gobain Gyproc",
    "in_stock": true
  },
  {
    "id": "2ae7741c-9272-4687-8372-6b7d05e556b8",
    "sku": "SKM-MSKM410A-12CEP5",
    "brand": "SKM",
    "category": "HVAC",
    "subcategory": "Split AC",
    "description_en": "SKM Decorative Split AC 1 Ton 12,000 BTU R410A, made in UAE, 5-year compressor warranty",
    "unit": "pcs",
    "price_aed": 1599,
    "vendor": "SKM Air Conditioning",
    "in_stock": true
  },
  {
    "id": "2b3d8507-2eb8-48ca-84ad-4c5515533401",
    "sku": "SKM-MSKM410A-18CEP5",
    "brand": "SKM",
    "category": "HVAC",
    "subcategory": "Split AC",
    "description_en": "SKM Decorative Split AC 1.5 Ton 18,000 BTU R410A, made in UAE, 5-year compressor warranty",
    "unit": "pcs",
    "price_aed": 1995,
    "vendor": "SKM Air Conditioning",
    "in_stock": true
  },
  {
    "id": "6c66d54f-0fb7-4531-8ae4-b34ec39770d0",
    "sku": "SKM-MSKM410A-12CEP5-INV",
    "brand": "SKM",
    "category": "HVAC",
    "subcategory": "Inverter Split AC",
    "description_en": "SKM Decorative Inverter Split AC 1 Ton 12,000 BTU, made in UAE, 5-year compressor warranty",
    "unit": "pcs",
    "price_aed": 2199,
    "vendor": "SKM Air Conditioning",
    "in_stock": true
  },
  {
    "id": "1aebc5dc-4202-4f05-9af1-a386f96b88f3",
    "sku": "SKM-MSKM410A-18CEP5-INV",
    "brand": "SKM",
    "category": "HVAC",
    "subcategory": "Inverter Split AC",
    "description_en": "SKM Decorative Inverter Split AC 1.5 Ton 18,000 BTU, made in UAE, 5-year compressor warranty",
    "unit": "pcs",
    "price_aed": 2595,
    "vendor": "SKM Air Conditioning",
    "in_stock": true
  },
  {
    "id": "1eb610f6-4c51-4c98-9ef8-223060c2f2e7",
    "sku": "SKM-MSKM410A-12LV",
    "brand": "SKM",
    "category": "HVAC",
    "subcategory": "Low-voltage Split",
    "description_en": "SKM Low-voltage Split AC 1 Ton 12,000 BTU, made in UAE, 5-year compressor warranty",
    "unit": "pcs",
    "price_aed": 1849,
    "vendor": "SKM Air Conditioning",
    "in_stock": true
  },
  {
    "id": "e69ec8bd-638d-47f0-a028-4c0e84293927",
    "sku": "SKM-MSKM410A-18LV",
    "brand": "SKM",
    "category": "HVAC",
    "subcategory": "Low-voltage Split",
    "description_en": "SKM Low-voltage Split AC 1.5 Ton 18,000 BTU, made in UAE, 5-year compressor warranty",
    "unit": "pcs",
    "price_aed": 2249,
    "vendor": "SKM Air Conditioning",
    "in_stock": true
  },
  {
    "id": "03b98187-12da-430f-8f39-15117e593cf0",
    "sku": "SKM-MSKM410A-24TC",
    "brand": "SKM",
    "category": "HVAC",
    "subcategory": "Tropical Split",
    "description_en": "SKM Tropical Climate Split AC 2 Ton 24,000 BTU, made in UAE, 5-year compressor warranty",
    "unit": "pcs",
    "price_aed": 2849,
    "vendor": "SKM Air Conditioning",
    "in_stock": true
  },
  {
    "id": "4699ef72-1597-44e4-a1a7-1acd4eeaa449",
    "sku": "SKM-MSKM410A-30TC",
    "brand": "SKM",
    "category": "HVAC",
    "subcategory": "Tropical Split",
    "description_en": "SKM Tropical Climate Split AC 2.5 Ton 30,000 BTU, made in UAE, 5-year compressor warranty",
    "unit": "pcs",
    "price_aed": 3249,
    "vendor": "SKM Air Conditioning",
    "in_stock": true
  },
  {
    "id": "c560ef12-3afa-40a7-9c1c-85ef13ef54f5",
    "sku": "SKM-DSKM410A-24CB",
    "brand": "SKM",
    "category": "HVAC",
    "subcategory": "Ducted Split AC",
    "description_en": "SKM Ducted Concealed AC 2 Ton 24,000 BTU R410A, made in UAE, 5-year compressor warranty",
    "unit": "pcs",
    "price_aed": 4295,
    "vendor": "SKM Air Conditioning",
    "in_stock": true
  },
  {
    "id": "a0d5f387-825f-45a3-9f3a-320afb1705a5",
    "sku": "SKM-DSKM410A-36CB",
    "brand": "SKM",
    "category": "HVAC",
    "subcategory": "Ducted Split AC",
    "description_en": "SKM Ducted Concealed AC 3 Ton 36,000 BTU R410A, made in UAE, 5-year compressor warranty",
    "unit": "pcs",
    "price_aed": 5495,
    "vendor": "SKM Air Conditioning",
    "in_stock": true
  },
  {
    "id": "2a0bfd11-ce87-41ee-af6d-d0798cca49c1",
    "sku": "SKM-CSKM-DUCT-200",
    "brand": "SKM",
    "category": "HVAC",
    "subcategory": "Ducting",
    "description_en": "SKM Insulated Flexible Duct 200mm x 10m, made in UAE, 5-year compressor warranty",
    "unit": "pcs",
    "price_aed": 245,
    "vendor": "SKM Air Conditioning",
    "in_stock": true
  },
  {
    "id": "8647394c-0be2-43a8-952a-c863b5cb90ee",
    "sku": "SKM-CSKM-DUCT-300",
    "brand": "SKM",
    "category": "HVAC",
    "subcategory": "Ducting",
    "description_en": "SKM Insulated Flexible Duct 300mm x 10m, made in UAE, 5-year compressor warranty",
    "unit": "pcs",
    "price_aed": 345,
    "vendor": "SKM Air Conditioning",
    "in_stock": true
  },
  {
    "id": "64f6fb6c-66f0-45b8-86cd-4b5f413cc56a",
    "sku": "SKM-CASS-410A-18",
    "brand": "SKM",
    "category": "HVAC",
    "subcategory": "Cassette AC",
    "description_en": "SKM Ceiling Cassette AC 1.5 Ton 18,000 BTU 4-Way, made in UAE, 5-year compressor warranty",
    "unit": "pcs",
    "price_aed": 3495,
    "vendor": "SKM Air Conditioning",
    "in_stock": true
  },
  {
    "id": "42f7a43c-6558-4dba-8d43-82dfa75478c2",
    "sku": "SKM-CASS-410A-24",
    "brand": "SKM",
    "category": "HVAC",
    "subcategory": "Cassette AC",
    "description_en": "SKM Ceiling Cassette AC 2 Ton 24,000 BTU 4-Way, made in UAE, 5-year compressor warranty",
    "unit": "pcs",
    "price_aed": 4295,
    "vendor": "SKM Air Conditioning",
    "in_stock": true
  },
  {
    "id": "3b6ef87e-7a90-4f37-8779-70ea993a0782",
    "sku": "SKM-WSKM-410-18",
    "brand": "SKM",
    "category": "HVAC",
    "subcategory": "Window AC",
    "description_en": "SKM Window AC 1.5 Ton 18,000 BTU R410A, made in UAE, 5-year compressor warranty",
    "unit": "pcs",
    "price_aed": 1495,
    "vendor": "SKM Air Conditioning",
    "in_stock": true
  },
  {
    "id": "214e4aa9-39e2-4a1a-9089-3a90b056f2ac",
    "sku": "SKM-WSKM-410-24",
    "brand": "SKM",
    "category": "HVAC",
    "subcategory": "Window AC",
    "description_en": "SKM Window AC 2 Ton 24,000 BTU R410A, made in UAE, 5-year compressor warranty",
    "unit": "pcs",
    "price_aed": 1895,
    "vendor": "SKM Air Conditioning",
    "in_stock": true
  },
  {
    "id": "a9ded4cd-5738-4e0e-8b01-0c0cdc80ee30",
    "sku": "MGT-3501",
    "brand": "Marble & Granite Trading",
    "category": "Stone & Slabs",
    "subcategory": "Marble Slab",
    "description_en": "Carrara White Marble Slab 20mm Polished (Carrara White)",
    "unit": "sqm",
    "price_aed": 695,
    "vendor": "Marble & Granite Trading LLC (Sharjah)",
    "in_stock": true
  },
  {
    "id": "763ddcea-e6b6-40be-b4ed-41c8b554db73",
    "sku": "MGT-3502",
    "brand": "Marble & Granite Trading",
    "category": "Stone & Slabs",
    "subcategory": "Marble Slab",
    "description_en": "Calacatta Gold Marble Slab 20mm Polished (Calacatta Gold)",
    "unit": "sqm",
    "price_aed": 1450,
    "vendor": "Marble & Granite Trading LLC (Sharjah)",
    "in_stock": true
  },
  {
    "id": "32d1bd21-0e97-40e2-9cad-c3ef046217c8",
    "sku": "MGT-3507",
    "brand": "Marble & Granite Trading",
    "category": "Stone & Slabs",
    "subcategory": "Travertine Slab",
    "description_en": "Beige Travertine Slab 20mm Honed (Travertine Beige)",
    "unit": "sqm",
    "price_aed": 425,
    "vendor": "Marble & Granite Trading LLC (Sharjah)",
    "in_stock": true
  },
  {
    "id": "87cda216-df0c-492d-b92f-05be921659dc",
    "sku": "MGT-3510",
    "brand": "Marble & Granite Trading",
    "category": "Stone & Slabs",
    "subcategory": "Onyx Slab",
    "description_en": "Onyx White Slab 20mm Polished Backlit (White Onyx)",
    "unit": "sqm",
    "price_aed": 2450,
    "vendor": "Marble & Granite Trading LLC (Sharjah)",
    "in_stock": true
  },
  {
    "id": "0e45df97-5474-4bde-ad5c-27068b0d5d1d",
    "sku": "MGT-3511",
    "brand": "Marble & Granite Trading",
    "category": "Stone & Slabs",
    "subcategory": "Onyx Slab",
    "description_en": "Onyx Honey Slab 20mm Polished Backlit (Honey Onyx)",
    "unit": "sqm",
    "price_aed": 2295,
    "vendor": "Marble & Granite Trading LLC (Sharjah)",
    "in_stock": true
  },
  {
    "id": "53395dcc-824f-4011-b600-2440cc3353f3",
    "sku": "MGT-3516",
    "brand": "Marble & Granite Trading",
    "category": "Stone & Slabs",
    "subcategory": "Granite Slab",
    "description_en": "Black Galaxy Granite Slab 20mm Polished (Black Galaxy)",
    "unit": "sqm",
    "price_aed": 295,
    "vendor": "Marble & Granite Trading LLC (Sharjah)",
    "in_stock": true
  },
  {
    "id": "5177e0b2-e5ee-425e-8380-9f9110fb1325",
    "sku": "MGT-3517",
    "brand": "Marble & Granite Trading",
    "category": "Stone & Slabs",
    "subcategory": "Granite Slab",
    "description_en": "Absolute Black Granite Slab 20mm Polished (Absolute Black)",
    "unit": "sqm",
    "price_aed": 285,
    "vendor": "Marble & Granite Trading LLC (Sharjah)",
    "in_stock": true
  },
  {
    "id": "f039e42c-8d00-497b-b2c3-8af47a023e64",
    "sku": "MGT-3524",
    "brand": "Marble & Granite Trading",
    "category": "Stone & Slabs",
    "subcategory": "Granite Tile",
    "description_en": "Premium Granite Pre-cut Tile 60x60 (Mixed)",
    "unit": "sqm",
    "price_aed": 195,
    "vendor": "Marble & Granite Trading LLC (Sharjah)",
    "in_stock": true
  },
  {
    "id": "0589b5e8-da3e-434f-b721-e486e6bade82",
    "sku": "MGT-3526",
    "brand": "Marble & Granite Trading",
    "category": "Stone & Slabs",
    "subcategory": "Porcelain Slab",
    "description_en": "Porcelain Slab Calacatta Effect 1600x3200x12 (Calacatta Effect)",
    "unit": "sqm",
    "price_aed": 595,
    "vendor": "Marble & Granite Trading LLC (Sharjah)",
    "in_stock": true
  },
  {
    "id": "42bad558-a325-4dcc-a958-f6c0223a2112",
    "sku": "MGT-3527",
    "brand": "Marble & Granite Trading",
    "category": "Stone & Slabs",
    "subcategory": "Porcelain Slab",
    "description_en": "Porcelain Slab Statuario Effect 1600x3200x12 (Statuario Effect)",
    "unit": "sqm",
    "price_aed": 645,
    "vendor": "Marble & Granite Trading LLC (Sharjah)",
    "in_stock": true
  },
  {
    "id": "58ddfd7f-9819-48ab-897b-1fb24335e07f",
    "sku": "SCH-MGU320118",
    "brand": "Schneider Electric",
    "category": "Electrical",
    "subcategory": "Switches/Sockets/MCB",
    "description_en": "Schneider Unica 1-Gang Switch 16A White",
    "unit": "pcs",
    "price_aed": 35,
    "vendor": "Scientechnic / ACE UAE (Schneider Electric)",
    "in_stock": true
  },
  {
    "id": "9ca49337-d050-4e13-a3fb-165b587ec725",
    "sku": "SCH-MGU320218",
    "brand": "Schneider Electric",
    "category": "Electrical",
    "subcategory": "Switches/Sockets/MCB",
    "description_en": "Schneider Unica 2-Gang Switch 16A White",
    "unit": "pcs",
    "price_aed": 45,
    "vendor": "Scientechnic / ACE UAE (Schneider Electric)",
    "in_stock": true
  },
  {
    "id": "c4cf956c-976b-4f46-a8bf-c44cc37a4571",
    "sku": "HIK-DS2CD1043G0I",
    "brand": "Hikvision",
    "category": "Security & CCTV",
    "subcategory": "Camera/DVR/NVR",
    "description_en": "Hikvision DS-2CD1043G0-I 4MP IR Bullet IP Camera",
    "unit": "pcs",
    "price_aed": 200,
    "vendor": "Al Shiraa (Hikvision UAE Distributor)",
    "in_stock": true
  },
  {
    "id": "72f6677f-00b0-4f86-89df-36670ae32516",
    "sku": "HIK-DS2CD1053G0I",
    "brand": "Hikvision",
    "category": "Security & CCTV",
    "subcategory": "Camera/DVR/NVR",
    "description_en": "Hikvision DS-2CD1053G0-I 5MP IR Bullet IP Camera H.265+",
    "unit": "pcs",
    "price_aed": 285,
    "vendor": "Al Shiraa (Hikvision UAE Distributor)",
    "in_stock": true
  }
] as unknown as PricingSku[];
